
var t_en = {"eintraege":"entries",
"eintrag":"entry",
"noprices":"Could not refresh prices",
"beendet":"ended",
"sekunden":"seconds",
"min":"min",
"sek":"sec",
"std":"h",
"tage":"days",
"tag":"day",
"vor1minute":"1 minute ago",
"vorxminuten":"%u minutes ago",
"vorxstunden":"%u hours ago",
"vor1tag":"1 day ago",
"vorxtagen":"%u days ago",
"invalidUrl":"Please enter a valid URL",

"alleanzeigen":"Show all",
"wunschliste":"Wish list",
"shops":"Shops",
"filter":"Filter videos",
"home":"Home",
"search":"Search",
"noentries":"no entries available",
"ratetext":"Please rate this extension",
"idbegin":"Move Top Link to the beginning",
"idend":"Move Top Link to the end",
"idedit":"Edit Top Link",
"iddel":"Delete Top Link",
"deffolder":"Folder",
"idbeginf":"Move folder to the beginning",
"idendf":"Move folder to the end",
"ideditf":"Edit folder name",
"iddelf":"Delete folder",
"langkey_preis":"Shopping",
"langkey_bilder":"Pictures",
"langkey_videos":"Videos",
"langkey_maps":"Maps",
"langkey_translate":"Translate",
"name":"Name:",
"url":"Adress:",
"searchurl":"Search adress (optional)",
"searchurl2":"Use %P1% as placeholder for the text to search for",
"apply":"Apply",
"cancel":"Cancel",
"ok":"Ok",
"done":"Apply changes" ,
"apps":"Apps",
"downloads":"Downloads",
"resethelp":"Reset help ballons",
"resethelp2":"Do you reallay want to reset all settings ?",
"resettheme":"Reset all",
"langKey_helpedit":"To move, delete or edit Top Links click 'Edit Top Links'",
"langKey_helpslideshow":"To control background images you can hide the Top Links by this button: <img src='./png/slide_toggle_dark.png'/>",
"langKey_helpsearch":"The most important searches allways available: Enter your search word and click for instance on images",
"langKey_helpsettings":"Click settings to customize the design of Startpage24",
"langKey_helpvideo":"To add items into your video list play a video of the sites listed at the bottom of this page and then click this icon above: ",
"langKey_helphomepage":"<h3>Important information</h3>To make sure Chrome comes up with Startpage24, please enter <a id='idChromeSettings' href='#'><b>Chrome settings</b></a> and then under <b>On startup</b> select the option<br/><b>Open the New Tab page</b>",
"langKey_helptoggle":"Click the background to show the Top Links again",
"langKey_helpdrag":"To move a Top Link, just click on it and move it the position you want",
"mostvisited":"most visited",
"ebaylist":"eBay wishlist",
"videolist":"videos",
"supported":"Supported video sites:",
"original":"Go to the original site",
"close":"close",
"ebayending":"Item<br/>ends in<br/>[sec]",
"buyitnow":"But-it-now",
"shipping":"Shipping costs",
"newToplink":"new Top Link",
"fullversion":"For thus function you need the full version of Startpage24. Do you want to install it now (for free) ?",
"noshipping":"no shipping costs",
"noborder":"No border",
"langKey_editToplinks":"Move videos",
"langKey_delall":"Delete all Top Links",
"langKey_addfolder":"Add folder",
"langKey_addToplink":"Add Top Link",
"langKey_settings":"Settings",
"langKey_firststart":"Startpage24",
"langKey_backup":"Save Startpage24 data into the cloud",
"langKey_backup2":"Click <b>Save now</b> to save all Top Links, Settings etc. into the cloud. You will get a short code, to restore your startpage later - even on another system or browser.<br><br>Please do not use this function, if other persons must not see this data.",
"langKey_backupnow":"Save now",
"langKey_restore":"Get Startpage24 data from the cloud",
"langKey_restore2":"Please enter the restore code you got when saving and then click <b>restore</b> to download all toplinks, settings etc. from the cloud.",
"langKey_restorenow":"Restore",
"pleasewait":"<center>Data beeing uploaded, please wait...</center>",
"langKey_backupresult":"<center>Please write down this key. With it, you can restore your settings:<br><br><font size='+2'><b>[key]</b></font></center>",
"langKey_restoreresult":"<center><br>Data has been restored successfully.<br><br></center>",
"langKey_restorefailed":"<center><br>The data for this key could not be read!<br><br></center>",
"langKey_restorefailed2":"<center><br>No data found for this key !<br><br></center>",
"langKey_icon":"Startpage24 menu icon",
"langKey_icon1":"Show on every page",
"langKey_icon2":"Show only on pages containing videos",
"langKey_icon3":"Never show",
"langKey_check1":"Show eBay wishlist and insert checkboxes on eBay sites",
"langKey_check2":"Show \"Apps\" folder",
"langKey_check3":"Show \"most visited\" folder",
"langKey_check4":"Show \"video\" folder",
"langKey_checknodefaults":"Customize colors and style",
"langKey_checkcountry":"Change Top Links when country changes",
"langKey_checkSlideshow":"Show background pictures to this topic:",
"langKey_bkcolor":"Select background color",
"langKey_textcolor":"Select text color",
"langKey_bordercolor":"Select color of the border below",
"langKey_trans":"Opacity of Top Links",
"langKey_border":"Select border",
"langKey_sync":"Synchronize Top Links with your Google account",
"langKey_ebaysec1":"Remember for eBay items",
"langKey_ebaysec2":"seconds before ending",
    
"langKey_country":"Select language",
"langKey_de":"German",
"langKey_en":"English",
}
 
var t_de = {"eintraege":"Einträge",
"eintrag":"Eintrag",
"noprices":"Konnte die Preise nicht aktualisieren",
"beendet":"Beendet",
"sekunden":"Sekunden",
"min":"Min",
"sek":"Sek",
"std":"Std",
"tage":"Tage",
"tag":"Tag",
"vor1minute":"vor 1 Minute",
"vorxminuten":"vor %u Minuten",
"vorxstunden":"vor %u Stunden",
"vor1tag":"vor 1 Tag",
"vorxtagen":"vor %u Tagen",
"invalidUrl":"Bitte geben Sie eine gültige Adresse ein",
"alleanzeigen":"Alle anzeigen",
"wunschliste":"Wunschliste",
"shops":"Shops",
"filter":"Filter Videos",
"home":"Startseite",
"search":"Suchen",
"noentries":"keine Einträge vorhanden",
"ratetext":"Bitte bewerten Sie diese Erweiterung",
"idbegin":"Toplink ganz nach vorne schieben",
"idend":"Toplink ganz nach hinten schieben",
"idedit":"Toplink-Eigenschaften ändern",
"iddel":"Toplink löschen",
"deffolder":"Ordner",
"idbeginf":"Ordner ganz nach vorne schieben",
"idendf":"Ordner ganz nach hinten schieben",
"ideditf":"Ordner-Eigenschaften ändern",
"iddelf":"Ordner löschen",
"langkey_preis":"Preissuche",
"langkey_bilder":"Bilder",
"langkey_videos":"Videos",
"langkey_maps":"Landkarten",
"langkey_translate":"Übersetzen",
"name":"Name:",
"url":"Adresse:",
"searchurl":"Such-Adresse (optional):",
"searchurl2":"Verwenden Sie %P1% als Platzhalter für den Suchtext",
"apply":"Übernehmen",
"cancel":"Abbrechen",
"ok":"Ok",
"done":"Änderungen übernehmen" ,
"apps":"Apps",
"downloads":"Downloads",
"resethelp":"Hilfeblasen wieder anzeigen",
"resethelp2":"Wollen Sie wirklich alle Einstellungen zurücksetzen?",
"resettheme":"Alles zurücksetzen",
"langKey_helpedit":"Zum Verschieben, Löschen und Ändern von Toplinks drücken Sie Toplinks bearbeiten",
"langKey_helpslideshow":"Zum Steuern der Hintergrundbilder können Sie mit dem Button <img src='./png/slide_toggle_dark.png'/> links unten die Toplinks verstecken",
"langKey_helpsearch":"Die wichtigsten Suchen haben Sie hier immer direkt verfügbar. Geben Sie Ihren Suchbegriff ein und klicken dann z.B. auf Bilder",
"langKey_helpsettings":"Klicken Sie Einstellungen, um zum Beispiel das Erscheinungsbild von Startpage24 zu ändern",
"langKey_helpvideo":"Um Einträge in Ihre Videoliste hinzuzufügen, spielen Sie ein Video auf eine der unten aufgeführten Seiten ab und klicken dann oben auf dieses Icon: ",
"langKey_helpdrag":"Um einen Toplink zur verschieben, klicken Sie auf ihn und ziehen ihn bei gedrückter Maustaste zur Zielposition",
"langKey_helphomepage":"<h3>Wichtige Information</h3>Um sicherzustellen, dass Startpage24 Ihre Startseite ist, gehen Sie bitte in die <a id='idChromeSettings' href='#'><b>Chrome-Einstellungen</b></a> und markieren dort unter <b>Beim Start</b> die Möglichkeit: <b>\"Neuer Tab\"-Seite öffnen</b>",
"langKey_helptoggle":"Klicken Sie einfach auf den Hintergrund um die Toplinks wieder anzuzeigen",
"mostvisited":"Meistbesucht",
"ebaylist":"eBay Wunschliste",
"videolist":"Videos",
"supported":"Unterstützte Videoseiten:",
"original":"Zur ursprünglichen Video-Seite wechseln",
"close":"schließen",
"ebayending":"Angebot<br/>ended in<br/>[sec]",
"buyitnow":"Sofort-Kaufen",
"shipping":"Versand",
"newToplink":"neuer Toplink",
"fullversion":"Für diese Funktion brauchen Sie die kostenlose Vollversion von Startpage24. Wollen Sie diese nun installieren ?",
"noshipping":"keine Versandkosten",
"noborder":"Kein Rahmen",
"langKey_editToplinks":"Videos verschieben",
"langKey_delall":"Alle Toplinks löschen",
"langKey_addfolder":"Ordner hinzufügen",
"langKey_addToplink":"Toplink hinzufügen",
"langKey_settings":"Einstellungen",
"langKey_firststart":"Startpage24",
"langKey_backup":"Startpage24-Daten in der Cloud speichern",
"langKey_backup2":"Klicken Sie <b>Jetzt sichern</b> um alle Toplinks, Einstellungen etc. in der Cloud zu speichern. Sie erhalten einen kurzen Code, mit dem Sie Ihre Startseite wiederherstellen können - auch auf anderen Systemen und Browsern.<br><br>Bitte benutzen Sie diese Funktion nicht, wenn andere Personen diese Daten nicht sehr dürfen.",
"langKey_backupnow":"Jetzt sichern",
"langKey_restore":"Startpage24-Daten aus der Cloud übernehmen",
"langKey_restore2":"Geben Sie den Wiederherstellungscode ein, den Sie beim Sichern erhalten haben und klicken <b>Wiederherstellen</b> um alle Toplinks, Einstellungen etc. aus der Cloud zu übernehmen.",
"langKey_restorenow":"Wiederherstellen",
"pleasewait":"<center>Daten werden hochgeladen, bitte warten...</center>",
"langKey_backupresult":"<center>Bitte notieren Sie sich diesen Schlüssel. Mit ihm können Sie Ihre Einstellungen wiederherstellen:<br><br><font size='+2'><b>[key]</b></font></center>",
"langKey_restoreresult":"<center><br>Die Daten wurden erfolgreich wiederhergestellt.<br><br></center>",
"langKey_restorefailed":"<center><br>Die Daten zu diesen Schlüssel konnten nicht korrekt gelesen werden!<br><br></center>",
"langKey_restorefailed2":"<center><br>Zu diesem Schlüssel wurden keine Daten gefunden!<br><br></center>",
"langKey_icon":"Startpage24-Menu-Icon",
"langKey_icon1":"Auf jeder Web-Seite anzeigen",
"langKey_icon2":"Nur auf Video-Seiten anzeigen",
"langKey_icon3":"Nie anzeigen",
"langKey_check1":"eBay Wunschliste anzeigen und Checkboxen auf eBay-Seiten einfügen",
"langKey_check2":"\"Apps\" anzeigen",
"langKey_check3":"\"Meistbesucht\" anzeigen",
"langKey_check4":"\"Video\"-Ordner anzeigen",
"langKey_checknodefaults":"Eigene Designeinstellungen verwenden",
"langKey_checkcountry":"Toplinks anpassen, wenn das Land geändert wird",
"langKey_checkSlideshow":"Zeige Hintergrundbilder zu diesem Thema:",
"langKey_bkcolor":"Hintergrundfarbe wählen",
"langKey_textcolor":"Textfarbe wählen",
"langKey_bordercolor":"Farbe des unteren Balkens wählen",
"langKey_trans":"Undurchsichtigkeit der Toplinks",
"langKey_border":"Rahmen wählen",
"langKey_sync":"Synchronisiere Toplinks mit Ihrem Google-Konto",
"langKey_ebaysec1":"Erinnere an eBay-Artikel",
"langKey_ebaysec2":"Sekunden vor Auktionsende",
    
"langKey_country":"Sprache wählen",
"langKey_de":"Deutsch",
"langKey_en":"Englisch",
}
 
var t = t_de;